# Generated by Django 4.1.5 on 2023-01-23 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dwitter", "0003_rename_dwitter_dweet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dweet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="dweets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
